### ISSUE TITLE
Broken link to Vercel in about

### ISSUE THREAD

**Issue by Michael-zea** [ZeaInc/zea-svelte-template#13]
![image](https://user-images.githubusercontent.com/65655656/106445755-6b46e600-644d-11eb-97e8-c6dc436da600.png)
![image](https://user-images.githubusercontent.com/65655656/106445793-7568e480-644d-11eb-8be9-73c41e23abf6.png)

**Comment by mauroporras** [comment]
Fixed and added some tags:
<img width="315" alt="Screen Shot 2021-02-01 at 09 17 02" src="https://user-images.githubusercontent.com/167700/106470238-41ea8200-646e-11eb-9779-9566084d1f50.png">
