### ISSUE TITLE
live demo is no longer deployed.

### ISSUE THREAD

**Issue by phtaylor** [ZeaInc/zea-svelte-template#73]
We have URLs in the README that no longer work. 
Can you see what has happened to our deployment?

https://svelte-template.zea.live/?zcad=data/gear_box_final_asm.zcad

https://svelte-template.zea.live/?zcad=data/Fidget-Spinner-2.zcad

https://svelte-template.zea.live/?zcad=data/HC_SRO4.zcad

Note: if there are errors in the deployment, just log an issue for me. I can fix them. ( most likely)

**Comment by mauroporras** [comment]
thought (network): the DNS config seems to be in good shape.

I will investigate further.

<img width="1037" alt="Screen Shot 2022-01-14 at 09 51 38" src="https://user-images.githubusercontent.com/167700/149535309-39a21ca8-3e53-4eba-b4c8-cb9e27867245.png">

**Comment by mauroporras** [comment]
thought: the last build was successful too.

It was 2 months ago. I will investigate further.

<img width="1052" alt="Screen Shot 2022-01-14 at 10 05 23" src="https://user-images.githubusercontent.com/167700/149537603-b5687276-c7a8-4e0e-b9e0-66a865c49e09.png">

**Comment by mauroporras** [comment]
thought: fixed.

<img width="1780" alt="Screen Shot 2022-01-14 at 11 07 24" src="https://user-images.githubusercontent.com/167700/149548012-86cd4d9b-99a2-4543-83c0-ce8001f2f4d5.png">

<img width="1780" alt="Screen Shot 2022-01-14 at 11 07 30" src="https://user-images.githubusercontent.com/167700/149548159-212b672e-e6e7-4772-862b-a9170f0c4a68.png">

<img width="1780" alt="Screen Shot 2022-01-14 at 11 07 27" src="https://user-images.githubusercontent.com/167700/149548105-61097dd8-1b87-47ec-891f-c0cf8555bdb4.png">
